Update Dockerfile

diff --git a/docker-build/Dockerfile b/docker-build/Dockerfile
--- a/docker-build/Dockerfile
+++ b/docker-build/Dockerfile
@@ -4,7 +4,8 @@ FROM ghcr.io/shipwright-io/shipwright-samples/golang:1.18 AS build
 
 COPY main.go .
 ENV CGO_ENABLED=0
-RUN ls -al .git
+RUN ls -al .git || echo "Git folder not found"
+
 RUN go build \
     -ldflags "-s -w -extldflags '-static'" \
     -o /tmp/helloworld \
